### ISSUE TITLE
[Feature Request] Config files

### ISSUE THREAD

**Issue by faelBrunnoS** [Chaos02/SubFolderLoader#1]
Would it be possible to do something similar with the configuration files in config folder? **_(.json and .toml)_**

It would be nice to be able to organize the configuration files for various mods too!
Every time I configure something through a text editor it's a headache. **_(Over 100 mods)_**

**Comment by Chaos02** [comment]
Hey, that's a really nice idea!!
I am unsure if it would be possible since mods generally provide their config file paths themselves *BUT* I think I could incorporate the same algorithm as in my mod into Forge's config file system.
The point where it gets complicated is:
- Mods call forges config provider to read/manage/generate the file. They assume its just in \mods
- I think I would need to scan the whole directory tree for every Mod that provides a config. OR
- Keep track of every file that has been registered where the user has put it. OR
- Replicate the directory structure from the \mods folder to \config and match the mods to their config that way.

All in all computationally expensive but with a class override, should be do-able!
Don't expect this feature in the near future tho as I'm still busy with [Adding transformer compatibility](https://github.com/Chaos02/SubFolderLoader/projects/1)

**Comment by faelBrunnoS** [comment]
Glad you liked the idea!
I imagine it must be really difficult, so who knows, maybe one day you'll put on this role!
I will be looking forward to it.

**Comment by Chaos02** [comment]
I'm always open for feedback and contribution - if you know someone that knows Java feel free to "invite" them to this thread!

**Comment by faelBrunnoS** [comment]
I'm studying Java to create mods for my server!  I'm not very familiar with this language, but when I can help here, I will definitely help you!

**Comment by Chaos02** [comment]
Yeah, dont hurry :P
This is also my first mod and I'm learning along the way, both git, GitHub AND Minecraft Java :) be sure to read the forge documentation when creating own mods :D
